name: color_extractor
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  image: 4.3.0
  cupertino_icons: ^1.0.8
  color_models: ^1.3.3
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  excel: ^4.0.6
  syncfusion_flutter_xlsio: ^25.1.35+1
  camera: ^0.11.1
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  ios: true
  image_path: "assets/logo.png"

